name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Willkommen zu deinem ersten Issue auf dem Noodle-Repository'
        pr-message: 'Willkommen zu deiner ersten Pull-Request auf dem Noodle-Repository'
